/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author esmondlam
 */
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class HomePage extends javax.swing.JFrame {
    

    /**
     * Creates new form HomePage
     */
 private static user user;
 private static ArrayList<user> allUsers;
private String selected;
    public HomePage(user user, ArrayList<user> allUsers) {
        this.user = user;
        this.allUsers = allUsers;
        
        this.setVisible(true);
        initComponents();
    }
    
    public HomePage(ArrayList<String[]> accountInfo, int index){
        initComponents();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTBS = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblbalnc = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        btnsendmoney = new javax.swing.JButton();
        btnlivestock = new javax.swing.JButton();
        btnhelp = new javax.swing.JButton();
        btnsignout = new javax.swing.JButton();
        btnaccount = new javax.swing.JButton();
        btnmovemoney = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTBS.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTBS.setText("TBS");

        lblWelcome.setText(user.getName());

        lblID.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblID.setText("Account #ID: " + user.getCardNumber());

        lblbalnc.setText("Balance:");
        String selectedAccount = user.getType();
        String targetAccountId = "";
        c checkingAccount = null;
        s savingsAccount = null;
                List<Account> accounts = user.getAccount();

                if (selectedAccount.equals("Checking")) {
                    targetAccountId = "Checking";
                    for (Account acc : accounts) {
                        if (acc.getAccountType().equals(targetAccountId)) {
                            checkingAccount = (c) acc;
                            lblMoney.setText(String.valueOf("$" + checkingAccount.getBalance()));
                        }
                    }
                } else if (selectedAccount.equals("Savings")) {
                    targetAccountId = "Savings";
                    for (Account acc : accounts) {
                        System.out.println(acc.getAccountType());
                        if (acc.getAccountType().equals(targetAccountId)) {
                            savingsAccount = (s) acc;
                            savingsAccount.getBalance();
                            lblMoney.setText(String.valueOf("$" + savingsAccount.getBalance()));
                        }
                    }
                }

        btnsendmoney.setText("Send Money");
        btnsendmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendmoneyActionPerformed(evt);
                user.getCardNumber();
                String selectedAccount = "Checking";
                new sendMoneyFrame(user, selectedAccount, allUsers);
            }
        });

        btnlivestock.setText("Live Stocks");
        btnlivestock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlivestockActionPerformed(evt);
            }
        });

        btnhelp.setText("Help");
        btnhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhelpActionPerformed(evt);
                System.out.println(user.getType());
                new FAQ(user, allUsers);
            }
        });

        btnsignout.setText("Sign Out");
        btnsignout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignoutActionPerformed(evt);
                dispose();
                SignIn newFrame = new SignIn();
                newFrame.setVisible(true);
            }
        });

        btnaccount.setText("Accounts");
        btnaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccountActionPerformed(evt);
                dispose();
                new AccountSelectorFrame(user, allUsers);
            }
        });

        btnmovemoney.setText("Move Money");
        btnmovemoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmovemoneyActionPerformed(evt);
                dispose();
                new moveMoneyFrame(user, allUsers);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblbalnc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMoney)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnmovemoney))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTBS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWelcome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnlivestock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnaccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnhelp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsignout))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsendmoney)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTBS)
                    .addComponent(lblWelcome))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(btnsendmoney))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbalnc)
                    .addComponent(lblMoney)
                    .addComponent(btnmovemoney))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlivestock)
                    .addComponent(btnsignout)
                    .addComponent(btnhelp)
                    .addComponent(btnaccount))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnsendmoneyActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnmovemoneyActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnlivestockActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void btnaccountActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btnhelpActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnsignoutActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new HomePage(user, allUsers ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnaccount;
    private javax.swing.JButton btnhelp;
    private javax.swing.JButton btnlivestock;
    private javax.swing.JButton btnmovemoney;
    private javax.swing.JButton btnsendmoney;
    private javax.swing.JButton btnsignout;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTBS;
    private javax.swing.JLabel lblbalnc;
    // End of variables declaration                   
}