import java.io.*;
import java.util.*;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author esmondlam
 */
public class SignIn extends javax.swing.JFrame {
    ArrayList<user> allUsers = new ArrayList<>();
    /**
     * Creates new form GUI
     */
    public SignIn() {
        initComponents();
    }
    
    public class AccountLoader{
        private ArrayList<String[]> accountList = new ArrayList<>();
        
        public void getAccountLists(String fileName) throws IOException{
            File file = new File(fileName);
System.out.println("Looking for file at: " + file.getAbsolutePath());
System.out.println("File exists: " + file.exists());
            BufferedReader reader = new BufferedReader(new FileReader(fileName));
            String accountNumber, fullName , password, spacer, checkingAccount, savingAccount;
            
            while (true) {
    accountNumber = reader.readLine();
    if (accountNumber == null) break;

    fullName = reader.readLine();
    password = reader.readLine();
    checkingAccount = reader.readLine();
    savingAccount = reader.readLine();
    spacer = reader.readLine(); // ---------------------------

    if (fullName == null || password == null || checkingAccount == null ||
        savingAccount == null || spacer == null) break;

    if (!spacer.startsWith("-")) continue;

    String[] userInfo = new String[5];
    userInfo[0] = accountNumber.split(":")[1].trim();
    userInfo[1] = fullName.split(":")[1].trim();
    userInfo[2] = password.split(":")[1].trim();  // <-- assign before printing
    userInfo[3] = checkingAccount.split(":")[1].trim();
    userInfo[4] = savingAccount.split(":")[1].trim();

    System.out.println("Loaded user: " + Arrays.toString(userInfo));

    user userObj = new user(userInfo[2], userInfo[0], userInfo[1]);
    c acc = new c(userObj.getCardNumber(), Double.parseDouble(userInfo[3]));
    s acc2 = new s(userObj.getCardNumber(), Double.parseDouble(userInfo[4]), 5);
    allUsers.add(userObj);
    userObj.addAccount(acc);
    userObj.addAccount(acc2);
    userObj.updateType("Checking");
    
    accountList.add(userInfo);
}
            reader.close(); //prevents memory leak

        } 
        public ArrayList<String[]> getAccountList(){
            return accountList;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        lblnoaccount = new javax.swing.JLabel();
        btnforgotpass = new javax.swing.JButton();
        btnlogin = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbltitle.setText("Tung Bank Sahur ");

        lbluser.setText("Username ");

        lblPass.setText("Password");

        lblnoaccount.setText("Don't have an account?");

        btnforgotpass.setText("Forgot Password?");
        btnforgotpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforgotpassActionPerformed(evt);
            }
        });

        btnlogin.setText("Login");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
                
            }
        });

        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbluser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtpass)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnforgotpass))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btnlogin)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lbltitle))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblnoaccount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnsignup)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbluser)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlogin))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnforgotpass)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnoaccount)
                    .addComponent(btnsignup))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {
        
        
        if (txtuser.getText().isEmpty() || txtpass.getText().isEmpty()) {
            System.out.println("Please input a username and password");
        }
        else if (!txtuser.getText().matches("[0-9]*")){
            System.out.println("Account number should have numbers only");
        } else if (txtuser.getText().length() != 16) {
            System.out.println("Account number must be 16 digits long");
        }else {
            
            try{    
                
                AccountLoader fileAccess = new AccountLoader();
                
                fileAccess.getAccountLists("AccountInfo.txt");
                ArrayList<String[]> accountList = fileAccess.getAccountList();
                
                boolean found = false;


    for (user a : allUsers){

    
    if(a.getCardNumber().equals(txtuser.getText()) && a.getPassword().equals(txtpass.getText())) {
        // login success
        
        System.out.println("Logging in");
        dispose();
        HomePage newFrame = new HomePage(a, allUsers);
        found = true;
        break;
    } else if (a.getCardNumber().equals(txtuser.getText())) {
        System.out.println("The password entered for this account is wrong");
        found = true;
        break;
    }
}

if (!found) {
    System.out.println("This account does not exist");
}
            }catch (Exception e) {
                System.out.println("Please input numerical numbers");
                System.out.println(e.getMessage());
            }        
        }
    }                                        

    private void btnforgotpassActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.setVisible(false);
        ForgotPassword newFrame = new ForgotPassword();
        newFrame.setVisible(true);
    }                                             

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.setVisible(false);
        SignUp newFrame = new SignUp();
        newFrame.setVisible(true);
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnforgotpass;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblnoaccount;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lbluser;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration                   
}