/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;
/**
 *
 * @author esmondlam
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        lblconfirmpass = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        txtconfirmpassword = new javax.swing.JPasswordField();
        btnconfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lbltitle.setText("Welcome to Tung Bank Sahur!");

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lblusername.setText("Full Name:");

        lblpassword.setText("Password:");

        lblconfirmpass.setText("Confirm Password:");

        btnconfirm.setText("Confirm");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lbltitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblpassword)
                                .addGap(18, 18, 18)
                                .addComponent(txtpassword))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblusername)
                                .addGap(18, 18, 18)
                                .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblconfirmpass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtconfirmpassword))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnconfirm)
                            .addComponent(btnback))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblconfirmpass)
                    .addComponent(txtconfirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnconfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnback)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String firstName = txtusername.getText();
        String accountNumber = String.valueOf(Math.random()).substring(2,17);
        char[] passwordChars = txtpassword.getPassword();
        String password = new String(passwordChars);
        char[] confirmChars = txtconfirmpassword.getPassword();
        String confirmPassword = new String(confirmChars);
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "passwords do not match!");
            return;
        }


        
        
        String inputReversed = new StringBuilder(accountNumber).reverse().toString();
        String[] cardNumberSplit = inputReversed.split(""); //splits numbers into individual digits
        ArrayList<Integer> cardNumberList = new ArrayList<>(); 
            int sum1 = 0; // sums to validate credit card
            int sum2 = 0; 
             
            for (String digit : cardNumberSplit) {
                cardNumberList.add(Integer.parseInt(digit)); //compiles seperated digits into a list
            }

            for (int i = 0; i < cardNumberList.size(); i++) { // for loop cycles through every iteration in the list
                int digit = cardNumberList.get(i); // digit is the list at a specific index


                if (i % 2 == 0) {// if the index is even, multiplies the number by 2
                    digit *= 2; 
                    if (digit > 9) {// if the number is greater than 9, subtracts 9 from the number
                        digit -= 9;
                    }
                    sum2 += digit; //if the index is even, add to sum 2
                } else {
                    sum1 += digit; //if the index is odd, add to sum 1
                }
            }
            int totalSum = sum1+sum2;
            int checkDigit = (10-(totalSum % 10)) % 10;
            String realAccountNumber = "";
            
            
              
            try (FileWriter writer = new FileWriter("AccountInfo.txt", true)) { // 'true' appends to the file
            if (firstName.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter your full name");
            } else if (password.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter a password");
            } else if (confirmPassword.isEmpty()){
                JOptionPane.showMessageDialog(null, "Please confirm your passwoord");
            }
            else{
            realAccountNumber = accountNumber + checkDigit;
                writer.write("Name: " + firstName + "\n");
                writer.write("Password: " + password + "\n");
                writer.write("Account Number: " + realAccountNumber + "\n");
                writer.write("Checking Balance: " + "0" + "\n");
                writer.write("Savings Balance: " + "0" + "\n");
                writer.write("---------------------------\n"); // separator for readability
                JOptionPane.showMessageDialog(null, "Welcome to Tung Bank Sahur!" + "\n" + "Your account number is: "  + realAccountNumber + "\n"+ "Please write this down and safe for future use, you will use this to sign in.");
                SignIn newFrame = new SignIn();
                this.setVisible(false);
                newFrame.setVisible(true);
            }
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "An error occured trying to compile your data");
            }

        }
                                      

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        this.setVisible(false);
        SignIn newFrame = new SignIn();
        newFrame.setVisible(true);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JPasswordField txtconfirmpassword;
    private javax.swing.JLabel lblconfirmpass;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration                   
}